server:
  port: 12345


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/temp
    username: tuser
    password: tuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
